apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploybyjenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: 266852548854.dkr.ecr.ap-northeast-2.amazonaws.com/test_jenkins:latest
        ports:
        - containerPort: 8088
